updated. added ssh check

diff --git a/bbwait b/bbwait
--- a/bbwait
+++ b/bbwait
@@ -1,9 +1,6 @@
 #!/bin/zsh -f
-# Purpose: Use BBEdit as your $EDITOR or $VISUAL, especially for visudo.
-# Install: This file should be installed as `/usr/local/bin/bbwait`
-#
-#	To use with `visudo` add the next line to /etc/sudoers file (without the '#'):
-# Defaults 	editor=/usr/local/bin/bbwait
+# Use BBEdit.app as your $EDITOR. This presumes that BBEdit.app and its
+# command line tool are both already installed
 #
 # From:	Timothy J. Luoma
 # Mail:	luomat at gmail dot com
@@ -11,35 +8,66 @@
 
 NAME="$0:t:r"
 
-	# this checkes to make sure that `bbedit` is found somewhere in the $PATH
 if ((! $+commands[bbedit] ))
 then
 
-		# if not, exit
-	echo "	$NAME: bbedit is required but not found in $PATH"
+	# note: if bbedit is a function or alias, it will come back not found
+
+	echo "$NAME: 'bbedit' is required but not found in $PATH"
 	exit 1
+
 fi
 
-# if `bbedit` is found, invoke it in a way that will wait until the window is closed before continuing
 
-bbedit 	--language 'Unix Shell Script' \
-		--create-unix \
-		--separate-windows \
-		--resume \
-		--wait \
-		-- "$@"
-
-EXIT="$?"
-
-if [ "$EXIT" = "0" ]
+if [ "$SSH" = "yes" ]
 then
-		echo "	$NAME: bbedit exited successfully."
-		exit 0
+
+	# we are logged in via SSH according to $SSH so we need to use a
+	# command line text editor. Add in your preferences here. The first one
+	# which is found will be used.
+
+	echo -n "$NAME: you are logged in via SSH (\$SSH = $SSH). Looking for alternate editor: "
+
+	if [ -x /usr/bin/nano ]
+	then
+			echo "found 'nano'"
+
+			/usr/bin/nano -w -- "$@"
+
+	elif [ -x /usr/bin/pico ]
+	then
+			echo "found 'pico'"
+			/usr/bin/pico -w -- "$@"
+
+	else
+			echo "could not find any alternative, so using 'vi'"
+			sleep 2
+			vi -- "$@"
+
+	fi
 
 else
-		echo "	$NAME: bbedit exited uncleanly (\$EXIT = $EXIT)"
 
-		exit 1
+	bbedit 	--language 'Unix Shell Script' \
+			--create-unix \
+			--new-window \
+			--resume \
+			--wait \
+			-- "$@"
+
+	EXIT="$?"
+
+	if [ "$EXIT" = "0" ]
+	then
+			echo "	$NAME: 'bbedit' exited successfully."
+			exit 0
+
+	else
+			echo "	$NAME: 'bbedit' exited uncleanly (\$EXIT = $EXIT)"
+
+			exit 1
+	fi
+
 fi
 
 #
